### ISSUE TITLE
Checkpoints broken link

### ISSUE THREAD

**Issue by MherMatevosyan** [LLNL/FAST#1]
Hi,

Interesting work. I would like to use your pre-trained models, however, the checkpoint link seems to be broken. Could you provide the pre-trained models?

**Comment by wderekjones** [comment]
Could you clarify your issue? What OS are you running? I tried accessing on OSX 10.14.6 and Ubuntu 20.04 and was able to access by pasting the link `ftp://gdo-bioinformatics.ucllnl.org/fast/pdbbind2016_model_checkpoints/` into the ubuntu file manager app on 20.04 and also on mac OSX 10.14.6 by using the finder app.

**Comment by wderekjones** [comment]
for further clarity, when accessing the FTP server, choose the "guest" option and you should see 3 tarballs available for transfer.
