### ISSUE TITLE
the core dataset

### ISSUE THREAD

**Issue by guzh970630** [LLNL/FAST#2]
I would like to ask, there is no INDEX_core_data.2016 in the "PDBbind_2016_plain_text_index" I downloaded from pdbbind. How did the author get it?

**Comment by wderekjones** [comment]
You can access this metadata from the pdbbind server `http://www.pdbbind.org.cn/` by download the `Index files of PDBbind` option on their page. you should get a compressed tar ball with this information.

**Comment by LoveChelsea** [comment]
actually no ' INDEX_core_data.2016 ' file in the Index files of PDBbind

**Comment by Xinxinatg** [comment]
> 

@LoveChelsea Hi I am coming across the same issue here, have you found the INDEX_core_data.2016 file?

**Comment by LoveChelsea** [comment]
> 

sorry，i can not find the  INDEX_core_data.2016 file， until now.

**Comment by Xinxinatg** [comment]
> > 
> 
> sorry，i can not find the INDEX_core_data.2016 file， until now.

@LoveChelsea seems like not only us are having the problem. https://gitlab.com/cheminfIBB/pafnucy/-/issues/9 in this issue, the person also cannot find this file.

**Comment by Xinxinatg** [comment]
@LoveChelsea I am now using INDEX_general_PL_data.2016 to replace  INDEX_core_data.2016 for now.

**Comment by LoveChelsea** [comment]
> @LoveChelsea I am now using INDEX_general_PL_data.2016 to replace INDEX_core_data.2016 for now.

yes，i have the same idea to solve this issue.HHHH

**Comment by Xinxinatg** [comment]
> > @LoveChelsea I am now using INDEX_general_PL_data.2016 to replace INDEX_core_data.2016 for now.
> 
> yes，i have the same idea to solve this issue.HHHH

@LoveChelsea thanks for your prompt reply! Btw have you come across the error when running parallel_chimera_preprocess_pdbbind_2018_refined_docking.sh? it says line 20: $1: unbound variable.

**Comment by LoveChelsea** [comment]
we can talk about those issue via WeChat

**Comment by LoveChelsea** [comment]
> > > @LoveChelsea I am now using INDEX_general_PL_data.2016 to replace INDEX_core_data.2016 for now.
> > 
> > 
> > yes，i have the same idea to solve this issue.HHHH
> 
> @LoveChelsea thanks for your prompt reply! Btw have you come across the error when running parallel_chimera_preprocess_pdbbind_2018_refined_docking.sh? it says line 20: $1: unbound variable.

we can talk about those issue via WeChat

**Comment by Xinxinatg** [comment]
> > > > @LoveChelsea I am now using INDEX_general_PL_data.2016 to replace INDEX_core_data.2016 for now.
> > > 
> > > 
> > > yes，i have the same idea to solve this issue.HHHH
> > 
> > 
> > @LoveChelsea thanks for your prompt reply! Btw have you come across the error when running parallel_chimera_preprocess_pdbbind_2018_refined_docking.sh? it says line 20: $1: unbound variable.
> 
> we can talk about those issue via WeChat

@LoveChelsea sure, thanks! my wechat id is nuaa-xxpeng
